/**
 * Keto plan PDF exporter — first consumer of the shared brandedPdf utility.
 *
 * Produces a 1–2 page premium document the client can save / share with
 * a spouse, parent, or doctor.
 */

import type { KetoTypeForCard } from "@/components/keto/InteractiveKetoTypeCard";
import { exportBrandedPdf, hexToRgb, type PdfSection } from "./brandedPdf";

export interface ExportKetoPlanOptions {
  ketoType: KetoTypeForCard;
  /** Hex color override; falls back to ketoType.color, then brand red. */
  themeColor?: string | null;
  /** Pulled into the footer as "Prepared for {clientName}". */
  clientName?: string | null;
  /** Optional pull-quote shown in the highlighted "Coach Read" block. */
  coachRead?: string | null;
}

function difficultyLabel(d?: string | null): string {
  if (d === "beginner") return "Beginner";
  if (d === "intermediate") return "Intermediate";
  if (d === "advanced") return "Advanced";
  return "Standard";
}

function safeFilenamePart(text: string): string {
  return text.replace(/[^a-z0-9]+/gi, "-").replace(/^-+|-+$/g, "");
}

export async function exportKetoPlanPdf(options: ExportKetoPlanOptions): Promise<void> {
  const { ketoType: kt, themeColor, clientName, coachRead } = options;
  const accent = hexToRgb(themeColor || kt.color);

  const subtitle =
    kt.subtitle ||
    kt.description ||
    `${kt.name} — your personalized ketogenic plan, built to keep you in fat-burning mode.`;

  const carbDetail =
    typeof kt.carb_limit_grams === "number" ? `≤${kt.carb_limit_grams}g net carbs` : undefined;

  const sections: PdfSection[] = [
    {
      type: "hero",
      eyebrow: "Your Personalized Keto Plan",
      title: `${kt.abbreviation} — ${kt.name}`,
      subtitle,
    },
    {
      type: "macros",
      tiles: [
        { label: "Fat", value: `${kt.fat_pct}%`, detail: "of daily calories" },
        { label: "Protein", value: `${kt.protein_pct}%`, detail: "of daily calories" },
        { label: "Carbs", value: `${kt.carbs_pct}%`, detail: carbDetail },
      ],
    },
  ];

  // How it works
  const overviewParas: string[] = [];
  if (kt.description) overviewParas.push(kt.description);
  if (kt.how_it_works && kt.how_it_works !== kt.description) {
    overviewParas.push(kt.how_it_works);
  }
  if (overviewParas.length > 0) {
    sections.push({ type: "heading", text: "How It Works" });
    for (const p of overviewParas) {
      sections.push({ type: "paragraph", text: p });
    }
  }

  // Built for
  if (kt.built_for && kt.built_for.length > 0) {
    sections.push({ type: "heading", text: "Built For You" });
    sections.push({ type: "bullets", items: kt.built_for });
  }

  // Daily rules
  sections.push({ type: "heading", text: "The Daily Rules" });
  sections.push({
    type: "numbered",
    items: [
      `Keep carbs at ${kt.carbs_pct}% of intake${
        carbDetail ? ` (${carbDetail}/day)` : ""
      }.`,
      `Hit fat at ~${kt.fat_pct}% of intake — don't fear the fat.`,
      `Protein at ~${kt.protein_pct}% — enough to protect muscle, not so much it kicks you out of ketosis.`,
      "Hydrate aggressively — water plus sodium, potassium, and magnesium.",
      "Plan meals around the eating window — no random snacking.",
    ],
  });

  // Macro schedule (key/value)
  sections.push({ type: "heading", text: "Macro Schedule" });
  sections.push({
    type: "keyValue",
    rows: [
      { label: "Fat", value: `${kt.fat_pct}% of daily calories` },
      { label: "Protein", value: `${kt.protein_pct}% of daily calories` },
      {
        label: "Carbs",
        value: `${kt.carbs_pct}%${carbDetail ? ` (${carbDetail})` : ""}`,
      },
      { label: "Difficulty", value: difficultyLabel(kt.difficulty) },
    ],
  });

  // Coach Read
  const quoteText =
    coachRead ||
    "Track for the first 2 weeks — guessing macros is the #1 reason people stall. Stay consistent: most people quit one week before it gets easy.";
  sections.push({ type: "heading", text: "Coach Read" });
  sections.push({
    type: "quote",
    text: quoteText,
    attribution: "Your KSOM-360 Coach",
  });

  const datePart = new Date().toISOString().slice(0, 10);
  const filename = `KSOM360-Keto-${safeFilenamePart(kt.abbreviation)}-${datePart}`;

  await exportBrandedPdf({
    filename,
    documentLabel: "Personalized Keto Plan",
    accentColor: accent,
    clientName,
    subject: `${kt.abbreviation} keto plan generated by KSOM-360`,
    sections,
  });
}
