/**
 * Smart Pace Daily Rollup
 * ----------------------------------------------------------------------------
 * Runs nightly. For every active Smart Pace goal:
 *  - If the client did NOT weigh in yesterday, add the missed-day target to
 *    their `current_debt_lbs`, increment `consecutive_missed_days`, and
 *    increment `consecutive_behind_days`.
 *  - Re-evaluate severity. If debt has crossed moderate/severe thresholds OR
 *    the client has hit 2+ consecutive missed days, write an
 *    `in_app_notifications` row to the trainer.
 *  - Also writes a "behind on pace" notification to the client themselves so
 *    the dashboard surfaces the issue immediately.
 */
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

interface SmartPaceGoalRow {
  id: string;
  client_id: string;
  daily_pace_lbs: number;
  current_debt_lbs: number | null;
  current_credit_lbs: number | null;
  consecutive_behind_days: number | null;
  consecutive_missed_days: number | null;
  last_weigh_in_date: string | null;
  start_date: string;
  status: string;
}

function todayISO(): string {
  return new Date().toISOString().slice(0, 10);
}
function yesterdayISO(): string {
  const d = new Date();
  d.setDate(d.getDate() - 1);
  return d.toISOString().slice(0, 10);
}
function daysBetween(aISO: string, bISO: string): number {
  const a = new Date(aISO + "T00:00:00Z").getTime();
  const b = new Date(bISO + "T00:00:00Z").getTime();
  return Math.max(0, Math.round((b - a) / 86_400_000));
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
  );

  const today = todayISO();
  const yesterday = yesterdayISO();

  const { data: goals, error: goalsErr } = await supabase
    .from("smart_pace_goals")
    .select(
      "id, client_id, daily_pace_lbs, current_debt_lbs, current_credit_lbs, consecutive_behind_days, consecutive_missed_days, last_weigh_in_date, start_date, status"
    )
    .eq("status", "active");

  if (goalsErr) {
    return new Response(
      JSON.stringify({ ok: false, error: goalsErr.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }

  const processed: any[] = [];
  const goalsList = (goals ?? []) as SmartPaceGoalRow[];

  for (const goal of goalsList) {
    const base = Number(goal.daily_pace_lbs) || 0;
    if (base <= 0) continue;

    const last = goal.last_weigh_in_date ?? goal.start_date;
    // Days the client failed to log a weigh-in (excluding today)
    const missedDays = daysBetween(last, today) - 1; // -1 because today not counted yet

    if (missedDays <= 0) continue; // weighed in yesterday or today, nothing to age

    // For each missed day, the client owes `base` lbs.
    let credit = Number(goal.current_credit_lbs) || 0;
    let debt = Number(goal.current_debt_lbs) || 0;
    let owed = base * missedDays;

    // Burn credit first
    const burn = Math.min(credit, owed);
    credit -= burn;
    owed -= burn;
    debt += owed;

    debt = Math.round(debt * 10) / 10;
    credit = Math.round(credit * 10) / 10;

    const newConsecutiveMissed =
      (goal.consecutive_missed_days || 0) + missedDays;
    const newConsecutiveBehind =
      (goal.consecutive_behind_days || 0) + missedDays;

    let severity: "mild" | "moderate" | "severe" = "mild";
    if (debt >= base * 3) severity = "severe";
    else if (debt >= base * 2) severity = "moderate";

    // 1. Update the goal row
    const { error: updErr } = await supabase
      .from("smart_pace_goals")
      .update({
        current_debt_lbs: debt,
        current_credit_lbs: credit,
        consecutive_missed_days: newConsecutiveMissed,
        consecutive_behind_days: newConsecutiveBehind,
      })
      .eq("id", goal.id);

    if (updErr) {
      console.error("[rollup] goal update failed", goal.id, updErr);
      continue;
    }

    // 2. Write daily-log rows marking each missed day
    for (let i = 1; i <= missedDays; i++) {
      const d = new Date();
      d.setDate(d.getDate() - i);
      const logDate = d.toISOString().slice(0, 10);
      await supabase.from("smart_pace_daily_log").upsert(
        {
          goal_id: goal.id,
          client_id: goal.client_id,
          log_date: logDate,
          target_loss_lbs: base,
          actual_loss_lbs: 0,
          weight_recorded: null,
          weight_source: "rollup_missed",
          status: "missed",
          debt_delta: base,
          credit_delta: 0,
          notes: "Auto-generated by daily rollup (no weigh-in)",
        },
        { onConflict: "goal_id,log_date" }
      );
    }

    // 3. Notify the client (always when behind)
    await supabase.from("in_app_notifications").insert({
      user_id: goal.client_id,
      title:
        severity === "severe"
          ? "You're significantly off pace"
          : severity === "moderate"
            ? "Catch-up needed"
            : "Don't forget to weigh in",
      body:
        missedDays === 1
          ? `You owe ${debt.toFixed(1)} lb to stay on pace. Weigh in today.`
          : `${missedDays} days without a weigh-in. Total to make up: ${debt.toFixed(1)} lb.`,
      category: "smart_pace",
    });

    // 4. Notify the trainer when moderate/severe OR 2+ missed
    if (severity !== "mild" || newConsecutiveMissed >= 2) {
      const { data: settings } = await supabase
        .from("client_feature_settings")
        .select("trainer_id")
        .eq("client_id", goal.client_id)
        .maybeSingle();

      const { data: clientProfile } = await supabase
        .from("profiles")
        .select("full_name")
        .eq("id", goal.client_id)
        .maybeSingle();

      if (settings?.trainer_id) {
        await supabase.from("in_app_notifications").insert({
          user_id: settings.trainer_id,
          title: `${clientProfile?.full_name ?? "A client"} is ${severity} on pace`,
          body: `${newConsecutiveMissed} missed day(s). Debt: ${debt.toFixed(1)} lb. Consider adjusting their goal.`,
          category: "smart_pace_trainer",
        });
      }
    }

    processed.push({
      goal_id: goal.id,
      client_id: goal.client_id,
      missedDays,
      newDebt: debt,
      severity,
    });
  }

  return new Response(
    JSON.stringify({ ok: true, processed: processed.length, details: processed }),
    { headers: { ...corsHeaders, "Content-Type": "application/json" }, status: 200 }
  );
});
