// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back. Useful for verifying the MCP connection.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var whoami_default = defineTool2({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's id and email as verified from the OAuth token.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const payload = { user_id: ctx.getUserId(), email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-my-clients.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function supabaseAsUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function notAuthed() {
  return {
    content: [{ type: "text", text: "Not authenticated" }],
    isError: true
  };
}
function errorResult(message) {
  return {
    content: [{ type: "text", text: message }],
    isError: true
  };
}
function jsonResult(payload, structuredKey) {
  const text = JSON.stringify(payload, null, 2);
  return {
    content: [{ type: "text", text }],
    structuredContent: structuredKey ? { [structuredKey]: payload } : payload
  };
}

// src/lib/mcp/tools/list-my-clients.ts
var list_my_clients_default = defineTool3({
  name: "list_my_clients",
  title: "List my clients",
  description: "List clients linked to the signed-in trainer via trainer_clients, joined with each client's profile (name, email).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const supabase = supabaseAsUser(ctx);
    const { data, error } = await supabase.from("trainer_clients").select("client_id, status, assigned_at, profiles:client_id ( full_name, email, engine_mode )").eq("trainer_id", ctx.getUserId());
    if (error) return errorResult(error.message);
    const rows = (data ?? []).map((r) => ({
      client_id: r.client_id,
      status: r.status,
      assigned_at: r.assigned_at,
      full_name: r.profiles?.full_name ?? null,
      email: r.profiles?.email ?? null,
      engine_mode: r.profiles?.engine_mode ?? null
    }));
    return jsonResult(rows, "clients");
  }
});

// src/lib/mcp/tools/get-client-progress.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25";
var get_client_progress_default = defineTool4({
  name: "get_client_progress",
  title: "Get client progress",
  description: "Return the latest weekly summary for a client (adherence score, avg score 7d, completion, trend, deltas). Requires the caller to be the client's trainer (RLS enforced).",
  inputSchema: {
    client_id: z2.string().uuid().describe("The client's profile id (UUID).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const supabase = supabaseAsUser(ctx);
    const { data, error } = await supabase.from("client_weekly_summaries").select("*").eq("client_id", client_id).order("updated_at", { ascending: false }).limit(1).maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) {
      return { content: [{ type: "text", text: "No progress summary found for this client." }] };
    }
    return jsonResult(data, "summary");
  }
});

// src/lib/mcp/tools/create-client-task.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25";
var create_client_task_default = defineTool5({
  name: "create_client_task",
  title: "Create client task",
  description: "Assign a task to one of the signed-in trainer's clients. The trainer_id is taken from the OAuth token, never from input.",
  inputSchema: {
    client_id: z3.string().uuid().describe("Target client's profile id."),
    name: z3.string().min(1).describe("Short task name shown to the client."),
    description: z3.string().optional().describe("Optional longer description."),
    task_type: z3.enum(["general", "progress_photo", "body_metrics", "form", "habit"]).default("general").describe("Task category."),
    due_date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Optional due date, YYYY-MM-DD.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ client_id, name, description, task_type, due_date }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const supabase = supabaseAsUser(ctx);
    const { data, error } = await supabase.from("client_tasks").insert({
      trainer_id: ctx.getUserId(),
      client_id,
      name,
      description: description ?? null,
      task_type,
      due_date: due_date ?? null
    }).select().single();
    if (error) return errorResult(error.message);
    return {
      content: [{ type: "text", text: `Task created: ${data.id}` }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/tools/list-client-tasks.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25";
var list_client_tasks_default = defineTool6({
  name: "list_client_tasks",
  title: "List client tasks",
  description: "List tasks for one of the signed-in trainer's clients. Filter by completion status.",
  inputSchema: {
    client_id: z4.string().uuid(),
    status: z4.enum(["open", "completed", "all"]).default("open"),
    limit: z4.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    let query = supabaseAsUser(ctx).from("client_tasks").select("id, name, description, task_type, due_date, completed_at, assigned_at").eq("client_id", client_id).order("assigned_at", { ascending: false }).limit(limit);
    if (status === "open") query = query.is("completed_at", null);
    if (status === "completed") query = query.not("completed_at", "is", null);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult(data ?? [], "tasks");
  }
});

// src/lib/mcp/tools/add-client-note.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25";
var add_client_note_default = defineTool7({
  name: "add_client_note",
  title: "Add client note",
  description: "Add a private trainer note about a client. Only visible to the trainer via RLS.",
  inputSchema: {
    client_id: z5.string().uuid(),
    content: z5.string().min(1)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ client_id, content }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const { data, error } = await supabaseAsUser(ctx).from("client_notes").insert({ trainer_id: ctx.getUserId(), client_id, content }).select().single();
    if (error) return errorResult(error.message);
    return {
      content: [{ type: "text", text: `Note saved: ${data.id}` }],
      structuredContent: { note: data }
    };
  }
});

// src/lib/mcp/tools/get-client-recent-workouts.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z6 } from "npm:zod@^3.25";
var get_client_recent_workouts_default = defineTool8({
  name: "get_client_recent_workouts",
  title: "Get client's recent workouts",
  description: "Return the client's most recent workout sessions (status, duration, completion %, difficulty rating, notes).",
  inputSchema: {
    client_id: z6.string().uuid(),
    limit: z6.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const { data, error } = await supabaseAsUser(ctx).from("workout_sessions").select(
      "id, started_at, completed_at, status, duration_seconds, completion_percentage, difficulty_rating, is_partial, notes"
    ).eq("client_id", client_id).order("started_at", { ascending: false }).limit(limit);
    if (error) return errorResult(error.message);
    return jsonResult(data ?? [], "workouts");
  }
});

// src/lib/mcp/tools/get-client-recent-fasts.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z7 } from "npm:zod@^3.25";
var get_client_recent_fasts_default = defineTool9({
  name: "get_client_recent_fasts",
  title: "Get client's recent fasts",
  description: "Return the client's most recent fasting sessions (target vs. actual hours, completion %, status).",
  inputSchema: {
    client_id: z7.string().uuid(),
    limit: z7.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const { data, error } = await supabaseAsUser(ctx).from("fasting_log").select("id, started_at, ended_at, target_hours, actual_hours, completion_pct, status, ended_early").eq("client_id", client_id).order("started_at", { ascending: false }).limit(limit);
    if (error) return errorResult(error.message);
    return jsonResult(data ?? [], "fasts");
  }
});

// src/lib/mcp/tools/send-coaching-message.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z8 } from "npm:zod@^3.25";
var send_coaching_message_default = defineTool10({
  name: "send_coaching_message",
  title: "Send coaching message to a client",
  description: "Post a coach message that appears in the client's dashboard coaching feed. Trainer-only.",
  inputSchema: {
    client_id: z8.string().uuid(),
    message: z8.string().min(1),
    action_text: z8.string().optional().describe("Optional CTA button label."),
    priority: z8.number().int().min(1).max(5).default(3),
    delivery_slot: z8.enum(["morning", "midday", "evening", "any"]).default("any")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ client_id, message, action_text, priority, delivery_slot }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await supabaseAsUser(ctx).from("coaching_messages").insert({
      client_id,
      coach_type: "trainer",
      message,
      action_text: action_text ?? null,
      priority,
      delivery_slot,
      message_date: today
    }).select().single();
    if (error) return errorResult(error.message);
    return {
      content: [{ type: "text", text: `Message queued for ${client_id}` }],
      structuredContent: { message: data }
    };
  }
});

// src/lib/mcp/tools/get-my-progress.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_my_progress_default = defineTool11({
  name: "get_my_progress",
  title: "Get my progress",
  description: "Return the signed-in client's latest weekly summary (adherence score, 7-day averages, trend, deltas).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const { data, error } = await supabaseAsUser(ctx).from("client_weekly_summaries").select("*").eq("client_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(1).maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return { content: [{ type: "text", text: "No weekly summary yet." }] };
    return jsonResult(data, "summary");
  }
});

// src/lib/mcp/tools/get-my-tasks.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z9 } from "npm:zod@^3.25";
var get_my_tasks_default = defineTool12({
  name: "get_my_tasks",
  title: "Get my tasks",
  description: "List the signed-in client's tasks. Filter by open, completed, or all.",
  inputSchema: {
    status: z9.enum(["open", "completed", "all"]).default("open"),
    limit: z9.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    let query = supabaseAsUser(ctx).from("client_tasks").select("id, name, description, task_type, due_date, completed_at, assigned_at, notes").eq("client_id", ctx.getUserId()).order("due_date", { ascending: true, nullsFirst: false }).limit(limit);
    if (status === "open") query = query.is("completed_at", null);
    if (status === "completed") query = query.not("completed_at", "is", null);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult(data ?? [], "tasks");
  }
});

// src/lib/mcp/tools/complete-task.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z10 } from "npm:zod@^3.25";
var complete_task_default = defineTool13({
  name: "complete_task",
  title: "Complete a task",
  description: "Mark a client_tasks row as completed (sets completed_at = now). RLS enforces the caller must own or coach the task.",
  inputSchema: {
    task_id: z10.string().uuid(),
    notes: z10.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ task_id, notes }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const patch = { completed_at: (/* @__PURE__ */ new Date()).toISOString() };
    if (notes) patch.notes = notes;
    const { data, error } = await supabaseAsUser(ctx).from("client_tasks").update(patch).eq("id", task_id).select().maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Task not found or not accessible.");
    return {
      content: [{ type: "text", text: `Task ${task_id} marked complete.` }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/tools/log-my-water.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z11 } from "npm:zod@^3.25";
var log_my_water_default = defineTool14({
  name: "log_my_water",
  title: "Log water intake",
  description: "Log a water intake entry (in ounces) for the signed-in client.",
  inputSchema: {
    amount_oz: z11.number().positive().max(500),
    logged_at: z11.string().datetime().optional().describe("Optional ISO timestamp; defaults to now.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ amount_oz, logged_at }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const { data, error } = await supabaseAsUser(ctx).from("water_log_entries").insert({
      client_id: ctx.getUserId(),
      amount_oz,
      logged_at: logged_at ?? (/* @__PURE__ */ new Date()).toISOString()
    }).select().single();
    if (error) return errorResult(error.message);
    return {
      content: [{ type: "text", text: `Logged ${amount_oz} oz of water.` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/tools/get-my-habits.ts
import { defineTool as defineTool15 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_my_habits_default = defineTool15({
  name: "get_my_habits",
  title: "Get my habits",
  description: "List the signed-in client's active habits with today's completion status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const supabase = supabaseAsUser(ctx);
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const [habitsRes, completionsRes] = await Promise.all([
      supabase.from("client_habits").select("id, name, description, goal_value, goal_unit, frequency, is_active").eq("client_id", ctx.getUserId()).eq("is_active", true),
      supabase.from("habit_completions").select("habit_id, value, completed_at").eq("client_id", ctx.getUserId()).eq("completion_date", today)
    ]);
    if (habitsRes.error) return errorResult(habitsRes.error.message);
    if (completionsRes.error) return errorResult(completionsRes.error.message);
    const completed = /* @__PURE__ */ new Map();
    for (const c of completionsRes.data ?? []) {
      completed.set(c.habit_id, { value: c.value, completed_at: c.completed_at });
    }
    const rows = (habitsRes.data ?? []).map((h) => ({
      ...h,
      completed_today: completed.has(h.id),
      today_value: completed.get(h.id)?.value ?? null
    }));
    return jsonResult(rows, "habits");
  }
});

// src/lib/mcp/tools/log-habit-completion.ts
import { defineTool as defineTool16 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z12 } from "npm:zod@^3.25";
var log_habit_completion_default = defineTool16({
  name: "log_habit_completion",
  title: "Log habit completion",
  description: "Mark one of the signed-in client's habits as completed for today (or a chosen date).",
  inputSchema: {
    habit_id: z12.string().uuid(),
    value: z12.number().optional().describe("Optional numeric amount (e.g. count/minutes)."),
    notes: z12.string().optional(),
    completion_date: z12.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("YYYY-MM-DD, defaults to today.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ habit_id, value, notes, completion_date }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const date = completion_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await supabaseAsUser(ctx).from("habit_completions").insert({
      habit_id,
      client_id: ctx.getUserId(),
      completion_date: date,
      completed_at: (/* @__PURE__ */ new Date()).toISOString(),
      value: value ?? null,
      notes: notes ?? null
    }).select().single();
    if (error) return errorResult(error.message);
    return {
      content: [{ type: "text", text: `Habit ${habit_id} logged for ${date}.` }],
      structuredContent: { completion: data }
    };
  }
});

// src/lib/mcp/tools/get-my-active-fast.ts
import { defineTool as defineTool17 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_my_active_fast_default = defineTool17({
  name: "get_my_active_fast",
  title: "Get my active fast",
  description: "Return the signed-in client's active fasting session (if any), including target and elapsed hours.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const { data, error } = await supabaseAsUser(ctx).from("fasting_log").select("id, started_at, ended_at, target_hours, actual_hours, completion_pct, status, ended_early").eq("client_id", ctx.getUserId()).is("ended_at", null).order("started_at", { ascending: false }).limit(1).maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return { content: [{ type: "text", text: "No active fast." }] };
    const startedAt = new Date(data.started_at).getTime();
    const elapsed_hours = Math.max(0, (Date.now() - startedAt) / 36e5);
    return jsonResult({ ...data, elapsed_hours: Number(elapsed_hours.toFixed(2)) }, "fast");
  }
});

// src/lib/mcp/tools/get-my-recent-workouts.ts
import { defineTool as defineTool18 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z13 } from "npm:zod@^3.25";
var get_my_recent_workouts_default = defineTool18({
  name: "get_my_recent_workouts",
  title: "Get my recent workouts",
  description: "Return the signed-in client's most recent workout sessions.",
  inputSchema: {
    limit: z13.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const { data, error } = await supabaseAsUser(ctx).from("workout_sessions").select(
      "id, started_at, completed_at, status, duration_seconds, completion_percentage, difficulty_rating, is_partial, notes"
    ).eq("client_id", ctx.getUserId()).order("started_at", { ascending: false }).limit(limit);
    if (error) return errorResult(error.message);
    return jsonResult(data ?? [], "workouts");
  }
});

// src/lib/mcp/tools/log-body-weight.ts
import { defineTool as defineTool19 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z14 } from "npm:zod@^3.25";
var log_body_weight_default = defineTool19({
  name: "log_body_weight",
  title: "Log body weight",
  description: "Log a body weight measurement (lbs) for the signed-in client. Automatically resolves the 'Weight' metric definition and reuses (or creates) the client's Weight metric row. A DB trigger will backfill the start weight of any active fitness goal if it isn't set yet.",
  inputSchema: {
    value_lbs: z14.number().positive().max(1500),
    recorded_at: z14.string().datetime().optional().describe("Optional ISO timestamp; defaults to now."),
    notes: z14.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ value_lbs, recorded_at, notes }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const supabase = supabaseAsUser(ctx);
    const clientId = ctx.getUserId();
    const { data: def, error: defErr } = await supabase.from("metric_definitions").select("id").eq("name", "Weight").eq("is_default", true).limit(1).maybeSingle();
    if (defErr) return errorResult(defErr.message);
    if (!def) return errorResult("Weight metric definition not found.");
    let { data: metric, error: metricErr } = await supabase.from("client_metrics").select("id").eq("client_id", clientId).eq("metric_definition_id", def.id).limit(1).maybeSingle();
    if (metricErr) return errorResult(metricErr.message);
    if (!metric) {
      const { data: created, error: createErr } = await supabase.from("client_metrics").insert({ client_id: clientId, metric_definition_id: def.id, is_pinned: true }).select("id").single();
      if (createErr) return errorResult(createErr.message);
      metric = created;
    }
    const { data: entry, error: entryErr } = await supabase.from("metric_entries").insert({
      client_id: clientId,
      client_metric_id: metric.id,
      value: value_lbs,
      recorded_at: recorded_at ?? (/* @__PURE__ */ new Date()).toISOString(),
      notes: notes ?? null
    }).select().single();
    if (entryErr) return errorResult(entryErr.message);
    return {
      content: [{ type: "text", text: `Weight logged: ${value_lbs} lbs.` }],
      structuredContent: { entry }
    };
  }
});

// src/lib/mcp/tools/log-meal-from-recipe.ts
import { defineTool as defineTool20 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z15 } from "npm:zod@^3.25";
var log_meal_from_recipe_default = defineTool20({
  name: "log_meal_from_recipe",
  title: "Log meal from recipe",
  description: "Log a meal for the signed-in client using an existing validated recipe. Macros are scaled by servings_eaten / recipe.servings. Writes to nutrition_logs, so it does not create free-text meals that would poison adaptive scoring.",
  inputSchema: {
    recipe_id: z15.string().uuid(),
    servings_eaten: z15.number().positive().max(20).default(1),
    log_date: z15.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("YYYY-MM-DD, defaults to today."),
    notes: z15.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ recipe_id, servings_eaten, log_date, notes }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const supabase = supabaseAsUser(ctx);
    const { data: recipe, error: recipeErr } = await supabase.from("recipes").select("id, name, calories, protein, carbs, fats, servings, is_valid, image_url").eq("id", recipe_id).maybeSingle();
    if (recipeErr) return errorResult(recipeErr.message);
    if (!recipe) return errorResult("Recipe not found or not accessible.");
    if (recipe.is_valid === false) return errorResult("Recipe is marked invalid; ask your coach to fix it before logging.");
    const baseServings = recipe.servings && recipe.servings > 0 ? recipe.servings : 1;
    const factor = servings_eaten / baseServings;
    const scale = (n) => n == null ? null : Math.round(Number(n) * factor * 100) / 100;
    const { data: entry, error: entryErr } = await supabase.from("nutrition_logs").insert({
      client_id: ctx.getUserId(),
      log_date: log_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      meal_name: `${recipe.name}${servings_eaten !== 1 ? ` (${servings_eaten}x)` : ""}`,
      calories: recipe.calories == null ? null : Math.round(Number(recipe.calories) * factor),
      protein: scale(recipe.protein),
      carbs: scale(recipe.carbs),
      fats: scale(recipe.fats),
      notes: notes ?? null,
      image_url: recipe.image_url ?? null
    }).select().single();
    if (entryErr) return errorResult(entryErr.message);
    return {
      content: [
        {
          type: "text",
          text: `Logged ${servings_eaten} serving(s) of "${recipe.name}" (~${entry.calories ?? "?"} kcal).`
        }
      ],
      structuredContent: { entry }
    };
  }
});

// src/lib/mcp/tools/reset-client-plan.ts
import { defineTool as defineTool21 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z16 } from "npm:zod@^3.25";
var reset_client_plan_default = defineTool21({
  name: "reset_client_plan",
  title: "Reset a client's plan (trainer)",
  description: "Clear the client's selected protocol, quick plan, and protocol start date in client_feature_settings. Destructive: their dashboard reverts to a clean slate and the realtime toast fires on their device. Requires the caller to be the client's trainer (enforced by RLS).",
  inputSchema: {
    client_id: z16.string().uuid()
  },
  annotations: {
    readOnlyHint: false,
    destructiveHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async ({ client_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const { data, error } = await supabaseAsUser(ctx).from("client_feature_settings").update({
      selected_protocol_id: null,
      selected_quick_plan_id: null,
      protocol_start_date: null,
      protocol_completed: false
    }).eq("client_id", client_id).select("client_id, selected_protocol_id, selected_quick_plan_id, protocol_start_date, protocol_completed").maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Client settings not found or not accessible.");
    return {
      content: [{ type: "text", text: `Plan reset for client ${client_id}.` }],
      structuredContent: { settings: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "eexxmfuknqttujecbcho";
var mcp_default = defineMcp({
  name: "ksom-360-mcp",
  title: "KSOM-360 MCP",
  version: "0.1.0",
  instructions: "Tools for KSOM-360. All calls run as the signed-in user with RLS enforced.\n\nConnectivity: `echo`, `whoami`.\n\nTrainer tools (require a trainer account): `list_my_clients`, `get_client_progress`, `get_client_recent_workouts`, `get_client_recent_fasts`, `list_client_tasks`, `create_client_task`, `add_client_note`, `send_coaching_message`.\n\nClient tools (act as the signed-in client): `get_my_progress`, `get_my_recent_workouts`, `get_my_tasks`, `complete_task`, `get_my_habits`, `log_habit_completion`, `log_my_water`, `get_my_active_fast`.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    echo_default,
    whoami_default,
    // Trainer
    list_my_clients_default,
    get_client_progress_default,
    get_client_recent_workouts_default,
    get_client_recent_fasts_default,
    list_client_tasks_default,
    create_client_task_default,
    add_client_note_default,
    send_coaching_message_default,
    reset_client_plan_default,
    // Client (acts as self)
    get_my_progress_default,
    get_my_recent_workouts_default,
    get_my_tasks_default,
    complete_task_default,
    get_my_habits_default,
    log_habit_completion_default,
    log_my_water_default,
    get_my_active_fast_default,
    log_body_weight_default,
    log_meal_from_recipe_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
