UPDATE recipes SET fats = 39 WHERE name = 'Apple Walnut Energy Salad with Honey';
UPDATE recipes SET fats = 44 WHERE name = 'Bacon & Eggs Metabolic Control Plate';
UPDATE recipes SET fats = 45 WHERE name = 'Bacon Avocado Power Omelet';
UPDATE recipes SET fats = 40 WHERE name = 'Bacon Egg Salad Lettuce Wraps';
UPDATE recipes SET fats = 0 WHERE name = 'Bare Bones Instant Beef Bone Broth';
UPDATE recipes SET fats = 36 WHERE name = 'Cajun Shrimp & Avocado Power Bowl';
UPDATE recipes SET fats = 38 WHERE name = 'Chili Lime Shrimp Power Bowl with Avocado';
UPDATE recipes SET fats = 40 WHERE name = 'Citrus Herb Steak Precision Plate';
UPDATE recipes SET fats = 47 WHERE name = 'Classic Chicken Cobb Power Bowl';
UPDATE recipes SET fats = 41 WHERE name = 'Clean Keto Egg & Avocado Control Bowl';
UPDATE recipes SET fats = 46 WHERE name = 'Crispy Chicken Control Bowl with Avocado & Eggs';
UPDATE recipes SET fats = 56 WHERE name = 'Double Cheeseburger Lettuce Wrap';
UPDATE recipes SET fats = 57 WHERE name = 'Garlic Butter Steak & Shrimp Power Plate';
UPDATE recipes SET fats = 36 WHERE name = 'Grilled Chicken Greek Bowl with Tzatziki';
UPDATE recipes SET fats = 20 WHERE name = 'Greek Yogurt Berry Power Bowl';
UPDATE recipes SET fats = 55 WHERE name = 'Halloumi Steak Breakfast Plate with Avocado';
UPDATE recipes SET fats = 7 WHERE name = 'High-Carb Fruit Recovery Bowl';
UPDATE recipes SET fats = 28 WHERE name = 'High Protein Flex Bowl with Eggs, Cottage Cheese & Berries';
UPDATE recipes SET fats = 48 WHERE name = 'Keto Antipasto Power Bowl';
UPDATE recipes SET fats = 50 WHERE name = 'Keto Cobb Power Bowl';
UPDATE recipes SET fats = 68 WHERE name = 'Keto Power Patties & Eggs Plate';
UPDATE recipes SET fats = 48 WHERE name = 'KSOM Breakfast Power Bowl with Eggs, Bacon & Avocado';
UPDATE recipes SET fats = 33 WHERE name = 'Lean Chicken Avocado Power Bowl';
UPDATE recipes SET fats = 48 WHERE name = 'Loaded Beef Lettuce Wrap Tacos';
UPDATE recipes SET fats = 45 WHERE name = 'Mediterranean Keto Mozzarella & Avocado Bowl';
UPDATE recipes SET fats = 31 WHERE name = 'Metabolic Flex Egg & Greens Bowl with Berries';
UPDATE recipes SET fats = 55 WHERE name = 'Protein Fuel Bowl with Eggs, Beef & Avocado';
UPDATE recipes SET fats = 44 WHERE name = 'Protein Scramble with Sausage & Spinach';
UPDATE recipes SET fats = 40 WHERE name = 'Real Life Protein Balance Plate with Eggs, Sausage & Fruit';
UPDATE recipes SET fats = 37 WHERE name = 'Scrambled Eggs, Grilled Sausage & Berry Performance Plate';
UPDATE recipes SET fats = 49 WHERE name = 'Steak, Eggs & Pineapple Performance Board';
UPDATE recipes SET fats = 52 WHERE name = 'Steak Scramble Plate with Avocado';
UPDATE recipes SET fats = 35 WHERE name = 'TKD Chicken Power Bowl with Corn & Avocado';
UPDATE recipes SET fats = 39 WHERE name = 'TKD Salmon Performance Plate with Plantains';
UPDATE recipes SET fats = 74 WHERE name = 'Ultimate Steak & Breakfast Feast Plate';